name: unit-tests
on: 
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3.5.0
        with:
          go-version-file: 'go.mod'

      - name: Test
        run: |
          go build -o lambstack/examples/simple/simple lambstack/examples/simple/simple.go
          go test ./... -v -coverprofile=coverage.txt -covermode=atomic
